version: '3'
services:
    app:
        restart: always
        container_name: market_ssua
        build:
            context: .
            dockerfile: ./Dockerfile
    redis:
        restart: always
        image: redis:6.0.10
        command: redis-server --port 6379
        container_name: redis6379
        hostname: redis6379
        labels:
          - "name=redis"
          - "mode=standalone"
        ports:
          - 6379:6379